[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.cpp_std = gnu++17
board_build.psram = enabled
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
monitor_speed = 115200
lib_ldf_mode = deep
extra_scripts = pre:scripts/pio_pre_tflm.py

build_flags =
    -w
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DESP_NN
    -DCONFIG_NN_OPTIMIZED=1
    -DCONFIG_IDF_TARGET_ESP32S3=1
    -DTF_LITE_STATIC_MEMORY
    -O3
    -DCORE_DEBUG_LEVEL=0
    -I.pio/libdeps/esp32s3/esp-tflite-micro/third_party/flatbuffers/include
    -I.pio/libdeps/esp32s3/esp-tflite-micro/third_party/gemmlowp
    -I.pio/libdeps/esp32s3/esp-tflite-micro/third_party/kissfft
    -I.pio/libdeps/esp32s3/esp-tflite-micro/third_party/ruy
    -I.pio/libdeps/esp32s3/esp-nn/include
    -I.pio/libdeps/esp32s3/esp-nn/src/common

lib_deps =
    https://github.com/espressif/esp32-camera
    https://github.com/espressif/esp-tflite-micro
    https://github.com/espressif/esp-nn
    https://github.com/mathieucarbou/ESPAsyncWebServer.git#v3.6.0
    https://github.com/mathieucarbou/AsyncTCP.git#v3.3.2
    bblanchon/ArduinoJson @ ^7.0.0
