[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.psram = enabled
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200

build_flags = 
    -w
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    https://github.com/espressif/esp32-camera
    tanakamasayuki/TensorFlowLite_ESP32
    https://github.com/mathieucarbou/ESPAsyncWebServer.git#v3.6.0
    https://github.com/mathieucarbou/AsyncTCP.git#v3.3.2
